### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by random-robbie** [eth0izzle/bucket-stream#1]
Hey dude,

This is awesome can you add a feature to log buckets it has found please?

if i get time ill see if i can throw a PR request.

**Comment by eth0izzle** [comment]
Will add something. In the meantime you can just `python bucket-stream.py > buckets.txt 2>&1 &`

**Comment by eth0izzle** [comment]
Thanks @Ekultek - how do you feel about creating a csv instead? `bucket_url,owner`

**Comment by barrett092** [comment]
also want to say how bad ass this tool is - awesome job

**Comment by Ekultek** [comment]
I think a csv would kind of defeat the purpose of a log file since there is not always going to be a known owner of the site @eth0izzle

**Comment by eth0izzle** [comment]
#3
