### ISSUE TITLE
503 when checking for buckets

### ISSUE THREAD

**Issue by random-robbie** [eth0izzle/bucket-stream#11]
Hey,

I think there might be a rate limit needed on when checking buckets.

[![Capture.png](https://s2.postimg.org/x5wlh6z7t/Capture.png)](https://postimg.org/image/ny4d0hs5h/)

**Comment by eth0izzle** [comment]
Thanks @random-robbie  - I suspected as much. Do you have any idea what the rate limit is, I can't find anything official from Amazon.

**Comment by random-robbie** [comment]
I am afraid i am not sure might need to put a sleep in for 1 second and go from there if a 503 is returned

**Comment by eth0izzle** [comment]
Would you mind doing some testing by increasing the timeout and seeing what works and then submit a PR? Thanks

**Comment by azzaj8** [comment]
Hey

Think this may be what we're looking for; 300 GET requests per second with a burst rate upto 800 per second.

http://docs.aws.amazon.com/AmazonS3/latest/dev/request-rate-perf-considerations.html

Request Rate and Performance Considerations

This topic discusses Amazon S3 best practices for optimizing performance depending on your request rates. If your workload in an Amazon S3 bucket routinely exceeds 100 PUT/LIST/DELETE requests per second or more than 300 GET requests per second, follow the guidelines in this topic to ensure the best performance and scalability. 

Amazon S3 scales to support very high request rates. If your request rate grows steadily, Amazon S3 automatically partitions your buckets as needed to support higher request rates. However, if you expect a rapid increase in the request rate for a bucket to more than 300 PUT/LIST/DELETE requests per second or more than 800 GET requests per second, we recommend that you open a support case to prepare for the workload and avoid any temporary limits on your request rate.

**Comment by eth0izzle** [comment]
My milage varies. Those rates are for a single bucket. They actually heavily limit requests to multiple buckets, about 10 requests a second. However if you are authenticated you can hammer away as much as you like. I'm pushing an update today which will help with this.
