### ISSUE TITLE
feature request -- write discovered domains to a log file

### ISSUE THREAD

**Issue by xxdesmus** [eth0izzle/bucket-stream#14]
I don't have the skills to actually write the PR myself, but I'd like to request the option to log discovered domains to a file.

I run today like:
```
python3 bucket-stream.py --skip-lets-encrypt -t 50 &>> out.txt
```

but it doesn't actually write to the file until I interrupt the app with a control+C ...so not sure if you're doing some buffering in the app that prevents real time writing to a file, but yeah -- feature request.

**Comment by azzaj8** [comment]
Hi

Dont beleive this should be a feature request as there is already a logging capability built in. It doesn't appear on the readme however if you look at the code you can see the below. 

```
139     parser.add_argument("-l", "--log", dest="log_to_file", default=False, action="store_true", 
140                         help="Log found buckets to a file buckets.log") 
```

Documentaiton will need updating to make this clear for everyone else.

Cheers

**Comment by eth0izzle** [comment]
Yes @azzaj8 is correct. I'm pushing a big update today so will fix that also.

**Comment by xxdesmus** [comment]
Thanks!
