### ISSUE TITLE
Quitting doesn't work

### ISSUE THREAD

**Issue by sa7mon** [eth0izzle/bucket-stream#19]
Once running, the only way to stop checking for buckets seems to be to mash Ctrl+C 3-4 times quickly. 

Hitting it once yields the following: 
![screen shot 2018-03-10 at 17 11 29](https://user-images.githubusercontent.com/3712226/37247763-3489db36-2486-11e8-8522-1a39f49eae58.png)

Tested using Python 3.6.4

**Comment by cjbarker** [comment]
This is fixed in pull request #20
