### ISSUE TITLE
Documentation for --skip-lets-encrypt

### ISSUE THREAD

**Issue by nareddyt** [eth0izzle/bucket-stream#26]
I looked through the README, codebase, and past issues, but I cannot determine a reason to enable the `--skip-lets-encrypt` feature flag. What are the pros/cons of this feature flag?

I can update the documentation with any explanation given in this issue. Thanks!

**Comment by eth0izzle** [comment]
Hi @nareddyt. It will ignore any certificates from the CT logs that were issued by the Let's Encrypt CA. When I wrote bucket-stream and in my testing I was seeing a lot of obviously illegitimate certificates being created. So the idea is with the `--skip-lets-encrypt` flag, you will get more results.
