### ISSUE TITLE
When using AWS Keys it won't scrub domains other than ".s3.amazonaws.com"

### ISSUE THREAD

**Issue by edwardgrubb3rd** [eth0izzle/bucket-stream#28]
I noticed when running this script without AWS Keys it catches buckets from multiple AWS locations, such as US-East- and US-West-. However, when using AWS Key and Secret it only logs domain at ".s3.amazonaws.com"

**Comment by plasticuproject** [comment]
I don't think I would consider this an issue, as the location is superfluous. For example the urls "http://foobar.s3-eu-west-1.amazonaws.com" and "http://foobar.s3.amazonaws.com" will still retrieve the same bucket. You should still catch the same buckets using either method. When using the AWS Key and Secret it uses the boto3 API (the __check_boto method) and when you are not it just uses the Requests library to parse the page content (the __check_html method). They are both still using the same permutations and expressions to parse the CertStream data. So they are both still catching the same buckets, neither one is leaving any out.

**Comment by plasticuproject** [comment]
I don't think I would consider this an issue, as the location is superfluous. For example the urls "http://foobar.s3-eu-west-1.amazonaws.com" and "http://foobar.s3.amazonaws.com" will still retrieve the same bucket/perform a redirect. You should still catch the same buckets using either method. When using the AWS Key and Secret it uses the boto3 API (the __check_boto method) and when you are not it just uses the Requests library to parse the page content (the __check_html method). They are both still using the same permutations and expressions to parse the CertStream data. So they are both still catching the same buckets, neither one is leaving any out.

**Comment by plasticuproject** [comment]
I don't think I would consider this an issue, as the location is superfluous. For example the urls "http://foobar.s3-eu-west-1.amazonaws.com" and "http://foobar.s3.amazonaws.com" will still retrieve the same bucket/perform a redirect. You should still catch the same buckets using either method. When using the AWS Key and Secret it uses the boto3 API (the __check_boto method) and when you are not it just uses the Requests library to parse the page content (the __check_html method). They are both still using the same permutations and expressions to parse the CertStream data. So they are both still catching the same buckets, neither one is leaving any out.

**Comment by eth0izzle** [comment]
It actually doesn't matter as bucket names are globally unique.
