### ISSUE TITLE
ImportError: cannot import name 'queue'

### ISSUE THREAD

**Issue by dzhenway** [eth0izzle/bucket-stream#31]
python bucket-stream.py -h
Traceback (most recent call last):
  File "bucket-stream.py", line 11, in <module>
    from queue import queue as Queue
ImportError: No module named queue

**Comment by dzhenway** [comment]
I tried edit import queue to import queue as Queue
but didnt solve my problem

**Comment by eth0izzle** [comment]
What version of python (python -v) and OS are you using?

**Comment by chankeypathak** [comment]
I have submitted a PR to fix this. https://github.com/eth0izzle/bucket-stream/pull/32
