### ISSUE TITLE
"No such bucket"

### ISSUE THREAD

**Issue by matiasw** [eth0izzle/bucket-stream#37]
Hi,
maybe I'm just stupid, but when using bucket-stream, I get eg. bucketname.s3.amazonaws.com, with ACLs = AllUsers: READ, READ_ACP | AuthenticatedUsers: (none). But, when I try to list the contents with aws2 CLI, like aws2 s3 ls s3://bucketname.s3.amazonaws.com, I get
> An error occurred (NoSuchBucket) when calling the ListObjectsV2 operation: The specified bucket does not exist

So what's going on? Am I doing something wrong?

**Comment by jbpratt78** [comment]
Hi @matiasw , I think to list the contents of the desired bucket correctly, you need to drop the `.s3.amazonaws.com` from the result and just use `s3://bucketname` when using the AWS CLI.

Here is a reference to help out:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro

**Comment by matiasw** [comment]
Hmm yes, it seems you are correct, even though the docs you linked also include the example "bucket.s3.amazonaws.com". 

But, it works with just the bucket name.
